export const localization = {
  en: {
    dir: 'ltr',
    brand: 'Mazen Academy',
    classroomTitle: 'Classroom',
    tagline: 'Learn to code after work',
    subtitle: 'Evening and weekend coding courses for adults with jobs. Small groups, real projects, and instructors who actually reply.',
    plant_seed: 'Start learning',
    explore: 'Browse courses',
    available_gardens: 'All courses',
    features: 'What you get',
    no_gardens_available: 'No courses open right now. We add new cohorts every few weeks — check back soon.',
    no_garden_seeds: 'No lessons in this course yet. The instructor is still recording them.',
    choose_spec: 'Pick one course and stick with it for a few weeks. That works better than five open tabs.',
    total_earnings: 'Total revenue',
    active_seekers: 'Active students',
    growth_rate: 'Completion rate',
    brand_subtitle: 'Evening coding courses for working adults',
    new_era: 'Evenings + weekends. Made for people with jobs.',
    hero_title_prefix: 'Learn to code',
    hero_title_highlight: 'after work',
    hero_title_suffix: '',
    hero_note: 'Most students put in 5–7 hours a week. No prior experience needed for beginner cohorts.',
    realtime_status: 'Enrollment open',
    plant_skill: 'Enroll',
    open_garden: 'Continue',
    my_gardens: 'My courses',
    secure_inbox: 'Inbox',
    view_profile: 'View profile',
    membership_paid: 'Enrolled',
    membership_free: 'Free',
    currency_egp: 'EGP',
    currency_try: 'TRY',
    admin_title: 'Admin',
    system_controller: 'Overview',
    security_logs: 'Security logs',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    courses: 'Courses',
    users: 'Students',
    settings: 'Settings',
    view_all: 'View all',
    launch_course: 'New course',
    last_seen: 'Last seen',
    ip_address: 'IP address',
    device: 'Device',
    location: 'Location',
    search_placeholder: 'Search by name or email...',
    new_registrations: 'New signups',
    avg_growth_rate: 'Avg. completion',
    security_alerts: 'Security alerts',
    chat_instructor: 'Message instructor',
    chat_placeholder: 'Write your message...',
    chat_send: 'Send',
    chat_transmitting: 'Sending...',
    forgot_password: 'Forgot password?',
    forgot_password_title: 'Reset your password',
    forgot_password_subtitle: 'Enter your email and we will send you a reset link.',
    send_reset_btn: 'Send reset link',
    reset_success_msg: 'Check your inbox for the reset link.',
    storage_used: 'Storage used',
    login_title: 'Log in',
    logout_session: 'Sign out',
    email_placeholder: 'you@example.com',
    password_placeholder: '••••••••',
    phone_placeholder: '+20 1XX XXX XXXX',
    sync_key_placeholder: '6-digit code',
    login_subtitle: 'Welcome back. Pick up where you left off.',
    email_address: 'Email',
    phone_wallet_num: 'Phone number',
    register_subtitle: 'Create an account to enroll. Takes about a minute.',
    email_or_phone: 'Email or phone',
    password: 'Password',
    already_have_account: 'Already have an account? Log in',
    quick_demo_login: 'Try demo',
    new_to_garden: 'New here?',
    create_account: 'Create account',
    verify_title: 'Check your email',
    verify_subtitle: 'We sent a 6-digit code to your email. Enter it below — it expires in a few minutes.',
    verify_btn: 'Verify',
    resend_timer: 'Resend in',
    resend_btn: 'Resend code',
    classroom_seeds: 'Lessons',
    classroom_rooted: 'Enrolled',
    classroom_path: 'You are here',
    progress_tracking: 'Your progress saves automatically',
    of: 'of',
    total: 'Total',
    remaining: 'Left',
    ask_question: 'Ask a question',
    question_placeholder: 'Stuck on something? Describe what you tried.',
    post_btn: 'Post',
    watermark_text: 'Licensed to you — please do not share',
    country_switch: 'Country',
    egypt: 'Egypt (EGP)',
    turkey: 'Turkey (TRY)',
    payment_method: 'Payment method',
    mobile_wallet: 'Mobile wallet (Vodafone Cash)',
    instapay: 'InstaPay',
    credit_card: 'Credit / debit card',
    papara: 'Papara',
    checkout_title: 'Checkout',
    checkout_btn: 'Pay now',
    price_label: 'Price',
    secure_badge: 'Secure checkout',
    need_help: 'Need help? Email us at support',
    notebook_title: 'My notes',
    add_note_btn: 'Save note',
    note_placeholder: 'Jot something down — you will thank yourself later...',
    capture_time: 'Link to current time',
    no_notes: 'No notes yet. Pause the video and write the part you keep forgetting.',
    user_page_title: 'My profile',
    user_page_badge: 'Verified student',
    enrolled_gardens: 'Enrolled courses',
    completed_seeds: 'Finished lessons',
    account_id: 'Account ID',
    security_level: 'Account status',
    membership_tier: 'Plan',
    registered_phone: 'Phone',
    joined_on: 'Joined',
    back_to_classroom: 'Back to course',
    back_to_landing: 'Back to courses',
    rights_reserved: 'All rights reserved.',
    my_gardens_desc: 'Courses you are enrolled in',
    enrolled_badge: 'Enrolled',
    pending_approval: 'Payment under review',
    previous_seed: 'Previous',
    next_seed: 'Next',
    no_queries_yet: 'No questions yet. Ask the first one — instructors check daily.',
    search_notes: 'Search notes...',
    download_notes: 'Copy notes',
    play_from_here: 'Play from here',
    delete_message: 'Delete',
    delete_confirm: 'Delete this message?',
    seed_not_completed: 'Lesson not finished',
    complete_seed_first: 'Finish the lesson first, then take the quiz.',
    no_quiz_questions: 'No quiz for this lesson yet.',
    quiz_review: 'Quiz',
    knowledge_check: 'Quick check',
    question_of: 'Question {current} of {total}',
    confirm_answer: 'Submit',
    checking_answer: 'Checking...',
    incorrect_review: 'Not quite. Rewatch that last section and try again.',
    try_again_btn: 'Try again',
    correct_excellent: 'Correct. Nice work.',
    next_question: 'Next question',
    complete: 'Done',
    previous_answer_incorrect: 'Last answer was off. One more try.',
    retry_btn: 'Retry',
    correct_answer: 'Correct',
    incorrect_try_again: 'Not correct — try again.',
    previous: 'Previous',
    next: 'Next',
    stream_error: 'Video did not load. Refresh and try again.',
    stream_auth_failed: 'Could not confirm access. Please log in again.',
    please_complete_checkout: 'This course needs payment first.',
    checkout_success_title: 'Payment received',
    checkout_transaction_msg: 'Transaction {id} confirmed.',
    checkout_redirecting: 'Setting up your access...',
    scan_or_copy: 'Scan or copy',
    send_exact_amount: 'Send exactly {amount} {currency} to enroll.',
    upload_screenshot: 'Upload receipt',
    confirm_phone_label: 'Phone number you paid from',
    mobile_wallet_number: 'Wallet number',
    papara_account: 'Papara account',
    secure_card_input: 'Card details',
    card_number: 'Card number',
    card_expiry: 'MM/YY',
    card_cvv: 'CVV',
    verifying_payment: 'Checking...',
    payment_required_alert: 'Please fill in all fields',
    drag_drop_browse: 'Drop your receipt here or click to browse',
    screenshot_attached: 'Receipt attached — click to change',
    encryption_notice: 'Only you and the instructor can read these.',
    refresh_analytics: 'Refresh',
    close_panel: 'Close',
    tab_cms: 'Content',
    tab_queries: 'Questions',
    tab_users: 'Students',
    tab_payments: 'Payments',
    tab_audit_logs: 'Logs',
    tab_quiz_management: 'Quizzes',
    tab_quiz_degrees: 'Scores',
    quiz_degrees_title: 'Quiz scores',
    quiz_degrees_desc: 'How everyone did, per lesson',
    no_quiz_data: 'No quiz answers yet.',
    loading: 'Loading...',
    name_col: 'Name',
    questions_col: 'Questions',
    correct_col: 'Right',
    wrong_col: 'Wrong',
    score_col: 'Score',
    stat_student_answers: 'Answers',
    stat_answers_submitted: 'Submitted',
    create_garden: 'New course',
    embed_seed: 'Add lesson',
    no_seeds_yet: 'No lessons in this course yet.',
    harvest_egypt: 'Egypt revenue',
    harvest_turkey: 'Turkey revenue',
    seekers_registered: 'Total students',
    active_now: 'Online now',
    garden_cms_manager: 'Course content',
    cms_subtitle: 'Lessons, quizzes, and prices live here',
    type_answer_here: 'Type your answer...',
    no_student_queries: 'No open questions. Nice.',
    weekly_analytics: 'This week',
    edit: 'Edit',
    del: 'Delete',
    quiz_short: 'Quiz',
    hide_seeds: 'Hide lessons',
    view_seeds: 'Show lessons',
    linked_seeds: 'Lessons',
    toggle_access: 'Change access',
    reply: 'Reply',
    search_mail: 'Search messages...',
    select_mail: 'Pick a message',
    status_online: 'Online',
    status_fallback: 'Offline preview',
    verification_secure_key: 'Code',
    cryptographic_seal: 'Secured',
    my_gardens_desc_continue: 'Keep going — even 20 minutes counts',
    student_growth_metrics: 'Your progress',
    seeds_bloomed: 'Lessons done',
    currently_studying: 'Now studying',
    completed: 'Done',
    total_seeds: 'lessons total',
    no_matching_seeds: 'Nothing matches those filters',
    adjust_filters: 'Try clearing a filter or two',
    sort_by: 'Sort:',
    default_order: 'Course order',
    difficulty_low_high: 'Easiest first',
    difficulty_high_low: 'Hardest first',
    duration_short_long: 'Shortest first',
    duration_long_short: 'Longest first',
    skill_tag_count: 'Most topics first',
    skill_tag: 'Topic',
    duration: 'Length',
    difficulty: 'Level',
    refine_reorder: 'Filter',
    reset: 'Reset',
    select_difficulty: 'Level:',
    select_duration: 'Length:',
    select_skill_tag: 'Topic:',
    previous_classroom: 'Course:',
    garden_questions_manager: 'Student questions',
    seekers_registry: 'Students',
    email_col: 'Email',
    phone_col: 'Phone',
    paid_gardens_col: 'Enrolled',
    verification_col: 'Verified',
    session_key_col: 'Session',
    actions_col: 'Actions',
    session_closed: 'Ended',
    verified: 'Yes',
    pending_verification: 'Pending',
    gardens_count_suffix: 'course(s)',
    none: 'None',
    smtp_diagnostics: 'Email check',
    smtp_status: 'Checking email connection...',
    smtp_indicator: 'Email status:',
    credentials_registry: 'Saved credentials',
    smtp_host: 'Host:',
    smtp_port: 'Port:',
    smtp_user: 'User:',
    smtp_from: 'From:',
    credential_state: 'Status:',
    smtp_test: 'Send test email',
    smtp_test_desc: 'Sends one test email to confirm delivery works.',
    email_placeholder_smtp: 'recipient@example.com',
    sending: 'Sending...',
    send_test: 'Send test',
    quiz_management_title: 'Quizzes',
    quiz_management_desc: 'Add a few questions per lesson. Short is fine.',
    refresh_quiz_data: 'Refresh',
    system_audit_logs: 'Admin log',
    audit_log_subtitle: 'Who changed what, and when',
    search_logs: 'Search logs...',
    no_matching_logs: 'No logs match that search.',
    no_logs: 'No logs yet.',
    no_transactions: 'No payments yet.',
    pending_status: 'Pending',
    approve_btn: 'Approve',
    reject_btn: 'Reject',
    export_csv: 'Export CSV',
    txn_id_col: 'Transaction',
    seeker_email_col: 'Student',
    garden_id_col: 'Course',
    amount_col: 'Amount',
    gateway_col: 'Method',
    proof_col: 'Receipt',
    status_col: 'Status',
    timestamp_col: 'Date',
    transaction_history: 'Payments',
    audit_log_desc: 'Payment records',
    smtp_missing_creds: 'Email is not set up, so codes will appear in the server console for now.',
    smtp_dispatch_success: 'Sent.',
    message_id: 'Message ID:',
    smtp_delivery_refused: 'Failed:',
    smtp_pass_loaded: 'Email password saved',
    not_configured: 'Not set',
    garden: 'Course',
    seed: 'Lesson',
    confirm_delete: 'Delete this? You cannot undo it.',
    answer_post_timeout: 'Took too long. Try again.',
    approval_failed: 'Could not approve',
    approval_request_failed: 'Approval request failed',
    rejection_failed: 'Could not reject',
    rejection_request_failed: 'Rejection request failed',
    deletion_error: 'Could not delete',
    cms_update_error: 'Could not save',
    bulk_limit_reached: 'Limit is 50 at a time — first 50 were added.',
    populate_lectures: 'Add lessons to the course first.',
    select_target_garden: 'Pick a course first.',
    bulk_insert_failed: 'Bulk add failed on the server.',
    network_upload_error: 'Upload failed: ',
    gardens: 'Courses',
    all_gardens: 'All courses',
    back_to_home: 'Home',
    browse_gardens: 'Browse courses',
    discover_courses: 'Cohorts starting soon — evening friendly',
    full_name: 'Full name',
    full_name_placeholder: 'e.g. Samira Haddad',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    difficult: 'Advanced',
    short_duration: 'Under 15 min',
    medium_duration: '15–30 min',
    long_duration: 'Over 30 min',
    payment_verified_pending: 'We got your receipt and are checking it. Usually under a day.',
    payment_approved: 'Payment approved',
    payment_rejected: 'Payment not approved',
    access_activated: 'You are enrolled. Start with lesson 1.',
    check_inbox_details: 'Details are in your inbox.',
    skills_acquired: 'What this course covers',
    expert_advice: 'An hour most evenings beats one long Sunday. That is the whole trick.',
    otp_dispatched: 'Code sent — check your inbox.',
    otp_verified: 'Verified. Your certificate is ready.',
    report_instruction: 'Finish every lesson to get your certificate.',
    garden_complete: 'Course complete — well done.',
    request_report: 'Get certificate',
    report_otp_label: 'Email code',
    verify_certificate: 'Verify and show certificate',
    otp_instruction: 'The code is in your inbox.',
    certificate_issued: 'Certificate sent to your email.',
    view_report: 'View certificate',
  },
  ar: {
    dir: 'rtl',
    brand: 'Mazen Academy',
    classroomTitle: 'الفصل',
    tagline: 'تعلّم البرمجة بعد الشغل',
    subtitle: 'دورات برمجة مسائية للكبار المشغولين. مجموعات صغيرة، مشاريع حقيقية، ومدرّس يرد عليك فعلاً.',
    plant_seed: 'ابدأ التعلم',
    explore: 'تصفح الدورات',
    available_gardens: 'كل الدورات',
    features: 'ماذا ستحصل عليه',
    no_gardens_available: 'لا توجد دورات مفتوحة الآن. نضيف مجموعات جديدة كل فترة.',
    no_garden_seeds: 'لا توجد دروس بعد. المدرّس ما زال يسجّلها.',
    choose_spec: 'اختر دورة واحدة وكمل فيها. هذا أفضل من خمس دورات مفتوحة مع بعض.',
    total_earnings: 'إجمالي الإيراد',
    active_seekers: 'الطلاب النشطون',
    growth_rate: 'نسبة الإكمال',
    brand_subtitle: 'دورات برمجة مسائية للموظفين',
    new_era: 'مساءً وعطلة نهاية الأسبوع. معمول للناس اللي عندها شغل.',
    hero_title_prefix: 'اتعلم البرمجة',
    hero_title_highlight: 'بعد الشغل',
    hero_title_suffix: '',
    hero_note: 'معظم الطلاب يذاكرون ٥-٧ ساعات أسبوعياً. لا تحتاج خبرة سابقة للمستوى المبتدئ.',
    realtime_status: 'التسجيل مفتوح',
    plant_skill: 'اشترك',
    open_garden: 'أكمل',
    my_gardens: 'دوراتي',
    secure_inbox: 'الرسائل',
    view_profile: 'الملف الشخصي',
    membership_paid: 'مشترك',
    membership_free: 'مجاني',
    currency_egp: 'ج.م',
    currency_try: 'ليرة',
    admin_title: 'الإدارة',
    system_controller: 'نظرة عامة',
    security_logs: 'سجلات الأمان',
    dashboard: 'لوحة التحكم',
    analytics: 'إحصائيات',
    courses: 'الدورات',
    users: 'الطلاب',
    settings: 'الإعدادات',
    view_all: 'عرض الكل',
    launch_course: 'دورة جديدة',
    last_seen: 'آخر ظهور',
    ip_address: 'العنوان',
    device: 'الجهاز',
    location: 'المكان',
    search_placeholder: 'ابحث بالاسم أو الإيميل...',
    new_registrations: 'تسجيلات جديدة',
    avg_growth_rate: 'متوسط الإكمال',
    security_alerts: 'تنبيهات',
    chat_instructor: 'راسل المدرّس',
    chat_placeholder: 'اكتب رسالتك...',
    chat_send: 'إرسال',
    chat_transmitting: 'يُرسل...',
    forgot_password: 'نسيت كلمة المرور؟',
    forgot_password_title: 'استرجاع كلمة المرور',
    forgot_password_subtitle: 'اكتب إيميلك وسنرسل لك رابط الاسترجاع.',
    send_reset_btn: 'إرسال الرابط',
    reset_success_msg: 'تفقد بريدك، أرسلنا الرابط.',
    storage_used: 'المساحة المستخدمة',
    login_title: 'تسجيل الدخول',
    logout_session: 'تسجيل الخروج',
    email_placeholder: 'you@example.com',
    password_placeholder: '••••••••',
    phone_placeholder: '01XXXXXXXXX',
    sync_key_placeholder: 'كود من ٦ أرقام',
    login_subtitle: 'أهلاً بعودتك. كمّل من حيث توقفت.',
    email_address: 'الإيميل',
    phone_wallet_num: 'رقم الهاتف',
    register_subtitle: 'اعمل حساب واشترك. الموضوع ياخد دقيقة.',
    email_or_phone: 'الإيميل أو الهاتف',
    password: 'كلمة المرور',
    already_have_account: 'عندك حساب؟ سجّل الدخول',
    quick_demo_login: 'جرّب الديمو',
    new_to_garden: 'جديد هنا؟',
    create_account: 'اعمل حساب',
    verify_title: 'تفقد إيميلك',
    verify_subtitle: 'أرسلنا كوداً من ٦ أرقام. اكتبه هنا قبل ما تنتهي صلاحيته.',
    verify_btn: 'تأكيد',
    resend_timer: 'إعادة الإرسال بعد',
    resend_btn: 'إعادة إرسال الكود',
    classroom_seeds: 'الدروس',
    classroom_rooted: 'مشترك',
    classroom_path: 'أنت هنا',
    progress_tracking: 'تقدمك يُحفظ تلقائياً',
    of: 'من',
    total: 'الإجمالي',
    remaining: 'المتبقي',
    ask_question: 'اسأل سؤالاً',
    question_placeholder: 'واقف في حاجة؟ اشرح جرّبت إيه.',
    post_btn: 'نشر',
    watermark_text: 'مرخّص لك — من فضلك لا تشاركه',
    country_switch: 'الدولة',
    egypt: 'مصر (جنيه)',
    turkey: 'تركيا (ليرة)',
    payment_method: 'طريقة الدفع',
    mobile_wallet: 'محفظة (فودافون كاش)',
    instapay: 'إنستاباي',
    credit_card: 'بطاقة بنكية',
    papara: 'بابارا',
    checkout_title: 'الدفع',
    checkout_btn: 'ادفع الآن',
    price_label: 'السعر',
    secure_badge: 'دفع آمن',
    need_help: 'محتاج مساعدة؟ ابعتلنا إيميل',
    notebook_title: 'ملاحظاتي',
    add_note_btn: 'حفظ',
    note_placeholder: 'اكتب ملاحظة سريعة...',
    capture_time: 'اربط بالوقت الحالي',
    no_notes: 'لا توجد ملاحظات. وقّف الفيديو واكتب الجزء الذي تنساه دائماً.',
    user_page_title: 'صفحتي',
    user_page_badge: 'طالب موثّق',
    enrolled_gardens: 'الدورات المشترك بها',
    completed_seeds: 'الدروس المنجزة',
    account_id: 'رقم الحساب',
    security_level: 'حالة الحساب',
    membership_tier: 'الخطة',
    registered_phone: 'الهاتف',
    joined_on: 'انضممت في',
    back_to_classroom: 'عودة للدورة',
    back_to_landing: 'عودة للدورات',
    rights_reserved: 'جميع الحقوق محفوظة.',
    my_gardens_desc: 'الدورات التي اشتركت فيها',
    enrolled_badge: 'مشترك',
    pending_approval: 'الدفع قيد المراجعة',
    previous_seed: 'السابق',
    next_seed: 'التالي',
    no_queries_yet: 'لا توجد أسئلة بعد. اسأل أول سؤال — المدرّس يتابع يومياً.',
    search_notes: 'ابحث في ملاحظاتك...',
    download_notes: 'نسخ الملاحظات',
    play_from_here: 'شغّل من هنا',
    delete_message: 'حذف',
    delete_confirm: 'حذف هذه الرسالة؟',
    seed_not_completed: 'الدرس لم يكتمل',
    complete_seed_first: 'خلّص الدرس الأول ثم حل الاختبار.',
    no_quiz_questions: 'لا يوجد اختبار لهذا الدرس بعد.',
    quiz_review: 'اختبار',
    knowledge_check: 'سؤال سريع',
    question_of: 'سؤال {current} من {total}',
    confirm_answer: 'تأكيد',
    checking_answer: 'نتحقق...',
    incorrect_review: 'ليست صحيحة. أعد مشاهدة الجزء الأخير وحاول مجدداً.',
    try_again_btn: 'حاول مجدداً',
    correct_excellent: 'صح. أحسنت.',
    next_question: 'السؤال التالي',
    complete: 'تم',
    previous_answer_incorrect: 'الإجابة الأخيرة لم تكن صحيحة. حاول مرة أخرى.',
    retry_btn: 'إعادة',
    correct_answer: 'صحيحة',
    incorrect_try_again: 'غير صحيحة — حاول مجدداً.',
    previous: 'السابق',
    next: 'التالي',
    stream_error: 'الفيديو لم يعمل. حدّث الصفحة وحاول مجدداً.',
    stream_auth_failed: 'تعذر تأكيد الدخول. سجّل الدخول مجدداً.',
    please_complete_checkout: 'هذه الدورة تحتاج الدفع أولاً.',
    checkout_success_title: 'تم استلام الدفع',
    checkout_transaction_msg: 'تم تأكيد العملية {id}.',
    checkout_redirecting: 'نجهّز دخولك...',
    scan_or_copy: 'امسح أو انسخ',
    send_exact_amount: 'أرسل {amount} {currency} بالضبط للاشتراك.',
    upload_screenshot: 'ارفع الإيصال',
    confirm_phone_label: 'الرقم الذي دفعت منه',
    mobile_wallet_number: 'رقم المحفظة',
    papara_account: 'حساب بابارا',
    secure_card_input: 'بيانات البطاقة',
    card_number: 'رقم البطاقة',
    card_expiry: 'شهر/سنة',
    card_cvv: 'CVV',
    verifying_payment: 'نتحقق...',
    payment_required_alert: 'من فضلك املأ كل الخانات',
    drag_drop_browse: 'اسحب الإيصال هنا أو اضغط للاختيار',
    screenshot_attached: 'تم إرفاق الإيصال — اضغط للتغيير',
    encryption_notice: 'أنت والمدرّس فقط من يرى هذه الرسائل.',
    refresh_analytics: 'تحديث',
    close_panel: 'إغلاق',
    tab_cms: 'المحتوى',
    tab_queries: 'الأسئلة',
    tab_users: 'الطلاب',
    tab_payments: 'المدفوعات',
    tab_audit_logs: 'السجلات',
    tab_quiz_management: 'الاختبارات',
    tab_quiz_degrees: 'الدرجات',
    quiz_degrees_title: 'درجات الاختبارات',
    quiz_degrees_desc: 'نتائج كل درس',
    no_quiz_data: 'لا توجد إجابات بعد.',
    loading: 'يحمّل...',
    name_col: 'الاسم',
    questions_col: 'الأسئلة',
    correct_col: 'صح',
    wrong_col: 'خطأ',
    score_col: 'الدرجة',
    stat_student_answers: 'الإجابات',
    stat_answers_submitted: 'المُرسل',
    create_garden: 'دورة جديدة',
    embed_seed: 'أضف درساً',
    no_seeds_yet: 'لا توجد دروس في هذه الدورة بعد.',
    harvest_egypt: 'إيراد مصر',
    harvest_turkey: 'إيراد تركيا',
    seekers_registered: 'إجمالي الطلاب',
    active_now: 'متصل الآن',
    garden_cms_manager: 'محتوى الدورة',
    cms_subtitle: 'الدروس والاختبارات والأسعار هنا',
    type_answer_here: 'اكتب إجابتك...',
    no_student_queries: 'لا توجد أسئلة مفتوحة.',
    weekly_analytics: 'هذا الأسبوع',
    edit: 'تعديل',
    del: 'حذف',
    quiz_short: 'اختبار',
    hide_seeds: 'إخفاء الدروس',
    view_seeds: 'عرض الدروس',
    linked_seeds: 'الدروس',
    toggle_access: 'تغيير الدخول',
    reply: 'رد',
    search_mail: 'ابحث في الرسائل...',
    select_mail: 'اختر رسالة',
    status_online: 'متصل',
    status_fallback: 'عرض دون اتصال',
    verification_secure_key: 'الكود',
    cryptographic_seal: 'مؤمّن',
    my_gardens_desc_continue: 'كمّل — حتى ٢٠ دقيقة تفرق',
    student_growth_metrics: 'تقدمك',
    seeds_bloomed: 'دروس منجزة',
    currently_studying: 'تذاكر الآن',
    completed: 'تم',
    total_seeds: 'درساً إجمالاً',
    no_matching_seeds: 'لا توجد نتائج مطابقة',
    adjust_filters: 'جرّب تمسح فلتر أو اثنين',
    sort_by: 'ترتيب:',
    default_order: 'ترتيب الدورة',
    difficulty_low_high: 'الأسهل أولاً',
    difficulty_high_low: 'الأصعب أولاً',
    duration_short_long: 'الأقصر أولاً',
    duration_long_short: 'الأطول أولاً',
    skill_tag_count: 'الأكثر مواضيع أولاً',
    skill_tag: 'الموضوع',
    duration: 'المدة',
    difficulty: 'المستوى',
    refine_reorder: 'فلترة',
    reset: 'مسح',
    select_difficulty: 'المستوى:',
    select_duration: 'المدة:',
    select_skill_tag: 'الموضوع:',
    previous_classroom: 'الدورة:',
    garden_questions_manager: 'أسئلة الطلاب',
    seekers_registry: 'الطلاب',
    email_col: 'الإيميل',
    phone_col: 'الهاتف',
    paid_gardens_col: 'مشترك',
    verification_col: 'موثّق',
    session_key_col: 'الجلسة',
    actions_col: 'إجراءات',
    session_closed: 'انتهت',
    verified: 'نعم',
    pending_verification: 'معلّق',
    gardens_count_suffix: 'دورة',
    none: 'لا يوجد',
    smtp_diagnostics: 'فحص الإيميل',
    smtp_status: 'نتحقق من اتصال الإيميل...',
    smtp_indicator: 'حالة الإيميل:',
    credentials_registry: 'البيانات المحفوظة',
    smtp_host: 'السيرفر:',
    smtp_port: 'المنفذ:',
    smtp_user: 'المستخدم:',
    smtp_from: 'المرسل:',
    credential_state: 'الحالة:',
    smtp_test: 'إرسال إيميل تجريبي',
    smtp_test_desc: 'يرسل إيميلاً واحداً للتأكد أن الإرسال يعمل.',
    email_placeholder_smtp: 'recipient@example.com',
    sending: 'يُرسل...',
    send_test: 'إرسال',
    quiz_management_title: 'الاختبارات',
    quiz_management_desc: 'أضف بضعة أسئلة لكل درس. المختصر يكفي.',
    refresh_quiz_data: 'تحديث',
    system_audit_logs: 'سجل الإدارة',
    audit_log_subtitle: 'من غيّر ماذا ومتى',
    search_logs: 'ابحث في السجلات...',
    no_matching_logs: 'لا توجد سجلات مطابقة.',
    no_logs: 'لا توجد سجلات بعد.',
    no_transactions: 'لا توجد مدفوعات بعد.',
    pending_status: 'معلّق',
    approve_btn: 'قبول',
    reject_btn: 'رفض',
    export_csv: 'تصدير CSV',
    txn_id_col: 'العملية',
    seeker_email_col: 'الطالب',
    garden_id_col: 'الدورة',
    amount_col: 'المبلغ',
    gateway_col: 'الطريقة',
    proof_col: 'الإيصال',
    status_col: 'الحالة',
    timestamp_col: 'التاريخ',
    transaction_history: 'المدفوعات',
    audit_log_desc: 'سجلات الدفع',
    smtp_missing_creds: 'الإيميل غير مضبوط، لذا ستظهر الأكواد في سجل السيرفر مؤقتاً.',
    smtp_dispatch_success: 'تم الإرسال.',
    message_id: 'رقم الرسالة:',
    smtp_delivery_refused: 'فشل:',
    smtp_pass_loaded: 'كلمة مرور الإيميل محفوظة',
    not_configured: 'غير مضبوط',
    garden: 'الدورة',
    seed: 'الدرس',
    confirm_delete: 'حذف هذا؟ لا يمكن التراجع.',
    answer_post_timeout: 'انتهت المهلة. حاول مجدداً.',
    approval_failed: 'تعذر القبول',
    approval_request_failed: 'فشل طلب القبول',
    rejection_failed: 'تعذر الرفض',
    rejection_request_failed: 'فشل طلب الرفض',
    deletion_error: 'تعذر الحذف',
    cms_update_error: 'تعذر الحفظ',
    bulk_limit_reached: 'الحد ٥٠ مرة واحدة — تمت إضافة أول ٥٠.',
    populate_lectures: 'أضف دروساً للدورة أولاً.',
    select_target_garden: 'اختر الدورة أولاً.',
    bulk_insert_failed: 'فشلت الإضافة الجماعية.',
    network_upload_error: 'فشل الرفع: ',
    gardens: 'الدورات',
    all_gardens: 'كل الدورات',
    back_to_home: 'الرئيسية',
    browse_gardens: 'تصفح الدورات',
    discover_courses: 'مجموعات جديدة قريباً — مناسبة للمساء',
    full_name: 'الاسم الكامل',
    full_name_placeholder: 'مثال: سميرة حداد',
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    difficult: 'متقدم',
    short_duration: 'أقل من ١٥ دقيقة',
    medium_duration: '١٥-٣٠ دقيقة',
    long_duration: 'أكثر من ٣٠ دقيقة',
    payment_verified_pending: 'استلمنا الإيصال ونراجعه. عادة خلال يوم.',
    payment_approved: 'تم قبول الدفع',
    payment_rejected: 'لم يُقبل الدفع',
    access_activated: 'تم اشتراكك. ابدأ من الدرس الأول.',
    check_inbox_details: 'التفاصيل في رسائلك.',
    skills_acquired: 'ماذا تغطي هذه الدورة',
    expert_advice: 'ساعة معظم المساءات أفضل من يوم طويل واحد. هذه هي الحيلة كلها.',
    otp_dispatched: 'أرسلنا الكود — تفقد بريدك.',
    otp_verified: 'تم التأكيد. شهادتك جاهزة.',
    report_instruction: 'أنهِ كل الدروس للحصول على الشهادة.',
    garden_complete: 'أنهيت الدورة — أحسنت.',
    request_report: 'الحصول على الشهادة',
    report_otp_label: 'كود الإيميل',
    verify_certificate: 'تأكيد وعرض الشهادة',
    otp_instruction: 'الكود موجود في رسائلك.',
    certificate_issued: 'أُرسلت الشهادة إلى إيميلك.',
    view_report: 'عرض الشهادة',
  },
  tr: {
    dir: 'ltr',
    brand: 'Mazen Academy',
    classroomTitle: 'Sınıf',
    tagline: 'İşten sonra kod öğren',
    subtitle: 'Çalışan yetişkinler için akşam ve hafta sonu kod kursları. Küçük gruplar, gerçek projeler, gerçekten cevap veren eğitmenler.',
    plant_seed: 'Öğrenmeye başla',
    explore: 'Kurslara göz at',
    available_gardens: 'Tüm kurslar',
    features: 'Neler var',
    no_gardens_available: 'Şu an açık kurs yok. Birkaç haftada bir yeni gruplar açıyoruz.',
    no_garden_seeds: 'Bu kursta henüz ders yok. Eğitmen hâlâ kaydediyor.',
    choose_spec: 'Bir kurs seç ve birkaç hafta onda kal. Beş sekmeden daha iyi sonuç verir.',
    total_earnings: 'Toplam gelir',
    active_seekers: 'Aktif öğrenciler',
    growth_rate: 'Bitirme oranı',
    brand_subtitle: 'Çalışanlar için akşam kod kursları',
    new_era: 'Akşam + hafta sonu. İşi olanlar için.',
    hero_title_prefix: 'İsten sonra',
    hero_title_highlight: 'kod öğren',
    hero_title_suffix: '',
    hero_note: 'Öğrencilerin çoğu haftada 5–7 saat ayırıyor. Başlangıç için deneyim gerekmez.',
    realtime_status: 'Kayıt açık',
    plant_skill: 'Kaydol',
    open_garden: 'Devam et',
    my_gardens: 'Kurslarım',
    secure_inbox: 'Mesajlar',
    view_profile: 'Profili gör',
    membership_paid: 'Kayıtlı',
    membership_free: 'Ücretsiz',
    currency_egp: 'EGP',
    currency_try: 'TRY',
    admin_title: 'Yönetim',
    system_controller: 'Genel bakış',
    security_logs: 'Güvenlik kayıtları',
    dashboard: 'Panel',
    analytics: 'İstatistik',
    courses: 'Kurslar',
    users: 'Öğrenciler',
    settings: 'Ayarlar',
    view_all: 'Tümünü gör',
    launch_course: 'Yeni kurs',
    last_seen: 'Son görülme',
    ip_address: 'IP',
    device: 'Cihaz',
    location: 'Konum',
    search_placeholder: 'İsim veya e-posta ile ara...',
    new_registrations: 'Yeni kayıtlar',
    avg_growth_rate: 'Ort. bitirme',
    security_alerts: 'Uyarılar',
    chat_instructor: 'Eğitmene yaz',
    chat_placeholder: 'Mesajını yaz...',
    chat_send: 'Gönder',
    chat_transmitting: 'Gönderiliyor...',
    forgot_password: 'Şifreni mi unuttun?',
    forgot_password_title: 'Şifreyi sıfırla',
    forgot_password_subtitle: 'E-postanı yaz, sıfırlama bağlantısı gönderelim.',
    send_reset_btn: 'Bağlantıyı gönder',
    reset_success_msg: 'Gelen kutunu kontrol et, bağlantıyı gönderdik.',
    storage_used: 'Kullanılan alan',
    login_title: 'Giriş yap',
    logout_session: 'Çıkış',
    email_placeholder: 'you@example.com',
    password_placeholder: '••••••••',
    phone_placeholder: '05XXXXXXXX',
    sync_key_placeholder: '6 haneli kod',
    login_subtitle: 'Tekrar hoş geldin. Kaldığın yerden devam et.',
    email_address: 'E-posta',
    phone_wallet_num: 'Telefon',
    register_subtitle: 'Kaydolmak için hesap aç. Bir dakika sürer.',
    email_or_phone: 'E-posta veya telefon',
    password: 'Şifre',
    already_have_account: 'Hesabın var mı? Giriş yap',
    quick_demo_login: 'Demoyu dene',
    new_to_garden: 'Yeni misin?',
    create_account: 'Hesap aç',
    verify_title: 'E-postanı kontrol et',
    verify_subtitle: '6 haneli bir kod gönderdik. Dakikalar içinde dolar — aşağıya gir.',
    verify_btn: 'Doğrula',
    resend_timer: 'Tekrar gönderim:',
    resend_btn: 'Kodu tekrar gönder',
    classroom_seeds: 'Dersler',
    classroom_rooted: 'Kayıtlı',
    classroom_path: 'Buradasın',
    progress_tracking: 'İlerlemen otomatik kaydedilir',
    of: '/',
    total: 'Toplam',
    remaining: 'Kalan',
    ask_question: 'Soru sor',
    question_placeholder: 'Takıldığın yer neresi? Neyi denediğini anlat.',
    post_btn: 'Paylaş',
    watermark_text: 'Sana lisanslı — lütfen paylaşma',
    country_switch: 'Ülke',
    egypt: 'Mısır (EGP)',
    turkey: 'Türkiye (TRY)',
    payment_method: 'Ödeme yöntemi',
    mobile_wallet: 'Mobil cüzdan (Vodafone Cash)',
    instapay: 'InstaPay',
    credit_card: 'Kart',
    papara: 'Papara',
    checkout_title: 'Ödeme',
    checkout_btn: 'Şimdi öde',
    price_label: 'Fiyat',
    secure_badge: 'Güvenli ödeme',
    need_help: 'Yardım mı lazım? E-posta at',
    notebook_title: 'Notlarım',
    add_note_btn: 'Kaydet',
    note_placeholder: 'Kısa bir not al...',
    capture_time: 'Şu ana bağla',
    no_notes: 'Henüz not yok. Videoyu durdur ve hep unuttuğun kısmı yaz.',
    user_page_title: 'Profilim',
    user_page_badge: 'Doğrulanmış öğrenci',
    enrolled_gardens: 'Kayıtlı kurslar',
    completed_seeds: 'Bitirilen dersler',
    account_id: 'Hesap no',
    security_level: 'Durum',
    membership_tier: 'Plan',
    registered_phone: 'Telefon',
    joined_on: 'Katılma',
    back_to_classroom: 'Kursa dön',
    back_to_landing: 'Kurslara dön',
    rights_reserved: 'Tüm hakları saklıdır.',
    my_gardens_desc: 'Kayıtlı olduğun kurslar',
    enrolled_badge: 'Kayıtlı',
    pending_approval: 'Ödeme inceleniyor',
    previous_seed: 'Önceki',
    next_seed: 'Sonraki',
    no_queries_yet: 'Henüz soru yok. İlkini sen sor — eğitmen her gün bakıyor.',
    search_notes: 'Notlarda ara...',
    download_notes: 'Notları kopyala',
    play_from_here: 'Buradan oynat',
    delete_message: 'Sil',
    delete_confirm: 'Bu mesaj silinsin mi?',
    seed_not_completed: 'Ders bitmedi',
    complete_seed_first: 'Önce dersi bitir, sonra quizi aç.',
    no_quiz_questions: 'Bu derste quiz yok.',
    quiz_review: 'Quiz',
    knowledge_check: 'Kısa kontrol',
    question_of: 'Soru {current} / {total}',
    confirm_answer: 'Gönder',
    checking_answer: 'Bakılıyor...',
    incorrect_review: 'Olmadı. Son bölümü tekrar izleyip dene.',
    try_again_btn: 'Tekrar dene',
    correct_excellent: 'Doğru. Güzel iş.',
    next_question: 'Sonraki soru',
    complete: 'Bitti',
    previous_answer_incorrect: 'Son cevap tutmadı. Bir daha dene.',
    retry_btn: 'Tekrar',
    correct_answer: 'Doğru',
    incorrect_try_again: 'Yanlış — tekrar dene.',
    previous: 'Önceki',
    next: 'Sonraki',
    stream_error: 'Video açılmadı. Sayfayı yenileyip dene.',
    stream_auth_failed: 'Erişim doğrulanamadı. Tekrar giriş yap.',
    please_complete_checkout: 'Önce ödeme gerekiyor.',
    checkout_success_title: 'Ödeme alındı',
    checkout_transaction_msg: '{id} numaralı işlem onaylandı.',
    checkout_redirecting: 'Erişimin hazırlanıyor...',
    scan_or_copy: 'Tara veya kopyala',
    send_exact_amount: 'Kaydolmak için tam {amount} {currency} gönder.',
    upload_screenshot: 'Dekont yükle',
    confirm_phone_label: 'Ödemeyi yaptığın numara',
    mobile_wallet_number: 'Cüzdan no',
    papara_account: 'Papara hesabı',
    secure_card_input: 'Kart bilgileri',
    card_number: 'Kart no',
    card_expiry: 'AA/YY',
    card_cvv: 'CVV',
    verifying_payment: 'Bakılıyor...',
    payment_required_alert: 'Lütfen tüm alanları doldur',
    drag_drop_browse: 'Dekontu buraya bırak veya seçmek için tıkla',
    screenshot_attached: 'Dekont eklendi — değiştirmek için tıkla',
    encryption_notice: 'Bunları sadece sen ve eğitmen görür.',
    refresh_analytics: 'Yenile',
    close_panel: 'Kapat',
    tab_cms: 'İçerik',
    tab_queries: 'Sorular',
    tab_users: 'Öğrenciler',
    tab_payments: 'Ödemeler',
    tab_audit_logs: 'Kayıtlar',
    tab_quiz_management: 'Quizler',
    tab_quiz_degrees: 'Puanlar',
    quiz_degrees_title: 'Quiz puanları',
    quiz_degrees_desc: 'Derslere göre sonuçlar',
    no_quiz_data: 'Henüz cevap yok.',
    loading: 'Yükleniyor...',
    name_col: 'İsim',
    questions_col: 'Soru',
    correct_col: 'Doğru',
    wrong_col: 'Yanlış',
    score_col: 'Puan',
    stat_student_answers: 'Cevaplar',
    stat_answers_submitted: 'Gönderilen',
    create_garden: 'Yeni kurs',
    embed_seed: 'Ders ekle',
    no_seeds_yet: 'Bu kursta ders yok.',
    harvest_egypt: 'Mısır geliri',
    harvest_turkey: 'Türkiye geliri',
    seekers_registered: 'Toplam öğrenci',
    active_now: 'Şu an çevrimiçi',
    garden_cms_manager: 'Kurs içeriği',
    cms_subtitle: 'Dersler, quizler ve fiyatlar burada',
    type_answer_here: 'Cevabını yaz...',
    no_student_queries: 'Açık soru yok.',
    weekly_analytics: 'Bu hafta',
    edit: 'Düzenle',
    del: 'Sil',
    quiz_short: 'Quiz',
    hide_seeds: 'Dersleri gizle',
    view_seeds: 'Dersleri göster',
    linked_seeds: 'Dersler',
    toggle_access: 'Erişimi değiştir',
    reply: 'Yanıtla',
    search_mail: 'Mesajlarda ara...',
    select_mail: 'Bir mesaj seç',
    status_online: 'Çevrimiçi',
    status_fallback: 'Çevrimdışı önizleme',
    verification_secure_key: 'Kod',
    cryptographic_seal: 'Korumalı',
    my_gardens_desc_continue: 'Devam et — 20 dakika bile fark eder',
    student_growth_metrics: 'İlerlemen',
    seeds_bloomed: 'Bitirilen ders',
    currently_studying: 'Şimdi çalışılan',
    completed: 'Bitti',
    total_seeds: 'ders toplam',
    no_matching_seeds: 'Bu filtreye uyan bir şey yok',
    adjust_filters: 'Bir-iki filtreyi temizlemeyi dene',
    sort_by: 'Sırala:',
    default_order: 'Kurs sırası',
    difficulty_low_high: 'Önce kolay',
    difficulty_high_low: 'Önce zor',
    duration_short_long: 'Önce kısa',
    duration_long_short: 'Önce uzun',
    skill_tag_count: 'Önce çok konulu',
    skill_tag: 'Konu',
    duration: 'Süre',
    difficulty: 'Seviye',
    refine_reorder: 'Filtrele',
    reset: 'Temizle',
    select_difficulty: 'Seviye:',
    select_duration: 'Süre:',
    select_skill_tag: 'Konu:',
    previous_classroom: 'Kurs:',
    garden_questions_manager: 'Öğrenci soruları',
    seekers_registry: 'Öğrenciler',
    email_col: 'E-posta',
    phone_col: 'Telefon',
    paid_gardens_col: 'Kayıtlı',
    verification_col: 'Doğrulama',
    session_key_col: 'Oturum',
    actions_col: 'İşlem',
    session_closed: 'Bitti',
    verified: 'Evet',
    pending_verification: 'Bekliyor',
    gardens_count_suffix: 'kurs',
    none: 'Yok',
    smtp_diagnostics: 'E-posta kontrolü',
    smtp_status: 'E-posta bağlantısı kontrol ediliyor...',
    smtp_indicator: 'Durum:',
    credentials_registry: 'Kayıtlı bilgiler',
    smtp_host: 'Sunucu:',
    smtp_port: 'Port:',
    smtp_user: 'Kullanıcı:',
    smtp_from: 'Gönderen:',
    credential_state: 'Durum:',
    smtp_test: 'Test e-postası',
    smtp_test_desc: 'Teslimatın çalıştığını görmek için bir tane gönderir.',
    email_placeholder_smtp: 'recipient@example.com',
    sending: 'Gönderiliyor...',
    send_test: 'Gönder',
    quiz_management_title: 'Quizler',
    quiz_management_desc: 'Ders başına birkaç soru ekle. Kısa olması sorun değil.',
    refresh_quiz_data: 'Yenile',
    system_audit_logs: 'Yönetim kaydı',
    audit_log_subtitle: 'Kim neyi ne zaman değiştirdi',
    search_logs: 'Kayıtlarda ara...',
    no_matching_logs: 'Aramana uyan kayıt yok.',
    no_logs: 'Henüz kayıt yok.',
    no_transactions: 'Henüz ödeme yok.',
    pending_status: 'Bekliyor',
    approve_btn: 'Onayla',
    reject_btn: 'Reddet',
    export_csv: 'CSV indir',
    txn_id_col: 'İşlem',
    seeker_email_col: 'Öğrenci',
    garden_id_col: 'Kurs',
    amount_col: 'Tutar',
    gateway_col: 'Yöntem',
    proof_col: 'Dekont',
    status_col: 'Durum',
    timestamp_col: 'Tarih',
    transaction_history: 'Ödemeler',
    audit_log_desc: 'Ödeme kayıtları',
    smtp_missing_creds: 'E-posta kurulu değil, kodlar şimdilik sunucu konsolunda görünür.',
    smtp_dispatch_success: 'Gönderildi.',
    message_id: 'Mesaj no:',
    smtp_delivery_refused: 'Hata:',
    smtp_pass_loaded: 'E-posta şifresi kayıtlı',
    not_configured: 'Kurulu değil',
    garden: 'Kurs',
    seed: 'Ders',
    confirm_delete: 'Silinsin mi? Geri alınamaz.',
    answer_post_timeout: 'Çok uzun sürdü. Tekrar dene.',
    approval_failed: 'Onaylanamadı',
    approval_request_failed: 'Onay isteği başarısız',
    rejection_failed: 'Reddedilemedi',
    rejection_request_failed: 'Ret isteği başarısız',
    deletion_error: 'Silinemedi',
    cms_update_error: 'Kaydedilemedi',
    bulk_limit_reached: 'Limit 50 — ilk 50 eklendi.',
    populate_lectures: 'Önce kursa ders ekle.',
    select_target_garden: 'Önce kurs seç.',
    bulk_insert_failed: 'Toplu ekleme başarısız.',
    network_upload_error: 'Yükleme başarısız: ',
    gardens: 'Kurslar',
    all_gardens: 'Tüm kurslar',
    back_to_home: 'Ana sayfa',
    browse_gardens: 'Kurslara göz at',
    discover_courses: 'Yakında yeni gruplar — akşam dostu',
    full_name: 'Ad soyad',
    full_name_placeholder: 'örn. Ahmet Yılmaz',
    beginner: 'Başlangıç',
    intermediate: 'Orta',
    advanced: 'İleri',
    difficult: 'İleri',
    short_duration: '15 dk altı',
    medium_duration: '15–30 dk',
    long_duration: '30 dk üstü',
    payment_verified_pending: 'Dekontu aldık, bakıyoruz. Genelde bir günden kısa sürer.',
    payment_approved: 'Ödeme onaylandı',
    payment_rejected: 'Ödeme onaylanmadı',
    access_activated: 'Kaydoldun. 1. dersten başla.',
    check_inbox_details: 'Detaylar mesajlarında.',
    skills_acquired: 'Bu kurs neleri kapsıyor',
    expert_advice: 'Çoğu akşam bir saat, tek bir uzun pazar gününden iyidir. İşin sırrı bu.',
    otp_dispatched: 'Kod gönderildi — gelen kutuna bak.',
    otp_verified: 'Doğrulandı. Sertifikan hazır.',
    report_instruction: 'Sertifika için her dersi bitir.',
    garden_complete: 'Kurs bitti — eline sağlık.',
    request_report: 'Sertifikayı al',
    report_otp_label: 'E-posta kodu',
    verify_certificate: 'Doğrula ve göster',
    otp_instruction: 'Kod mesajlarında.',
    certificate_issued: 'Sertifika e-postana gönderildi.',
    view_report: 'Sertifikayı gör',
  }
};
